name = "PeaceVote"
uuid = "129db535-0459-46ad-8d3d-b1fb8f318c74"
authors = ["akels <akels14@gmail.com>"]
version = "0.2.3"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1"

[extras]
PeaceCypher = "7743456c-e0c5-4477-a2b6-196c240b0368"

[targets]
test = ["PeaceCypher"]
