name = "PeaceVote"
uuid = "129db535-0459-46ad-8d3d-b1fb8f318c74"
authors = ["akels <akels14@gmail.com>"]
version = "0.1.3"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
julia = "1"

[extras]
CryptoGroups = "bc997328-bedd-407e-bcd3-5758e064a52d"
CryptoSignatures = "35cc5888-0c46-470e-89c7-eafcaf79a1aa"
Nettle = "49dea1ee-f6fa-5aa6-9a11-8816cee7d4b9"

[targets]
test = ["CryptoGroups","CryptoSignatures","Nettle"]